### ISSUE TITLE
App crash when i split screen on my android 7.0

### ISSUE THREAD

**Issue by iamowomizz** [gauravjot/android-noad-music-player#10]
#### Describe the bug
The app crashes when I split screen on my android

#### Steps To Reproduce
Launch the app
Accept all permissions
Then split screen

#### Expected behavior
I expect the app not to crash when I split screen on my android

#### Device and Version
Device (Infinix s2pro)
Version (7.0)
App version 0.9.4

**Comment by gauravjot** [comment]
I will look into it and will most likely patch it in next update. Stay tuned :)

**Comment by gauravjot** [comment]
I have found the solution and have fixed it. An update will be available in the next few hours. Thanks for posting the issue!
