### ISSUE TITLE
Bug: Delete doesn't work on artist page

### ISSUE THREAD

**Issue by darewealth** [gauravjot/android-noad-music-player#2]
### Describe the bug.

When I play music on the app and then click on the 3 dots on the top right corner of the app.  Then I click on  go to artist.  I found a function to delete there,  and I tried to delete the music but it doesn't delete.  

### Steps to reproduce.

* Launch the app

* Click on  songs feature

* Click on the 3 dots and click on 'Go to artist'

* Click on the 3 dots again (down on the music)  there and use the delete function.  It doesn't work.

### Expected Behaviour

I expect the delete function should  delete any music.

### Screen recording
https://youtu.be/r4-1hYyl3IY

### Devices and Versions)

* Device: [Gionee]

* Version [7.0]

* App version [0.9.20190524-2]

**Comment by gauravjot** [comment]
App currently will not delete any files on the device because it only requires permission to read files. Delete option has been removed from everywhere in the app.
