### ISSUE TITLE
v0.9.20290524 Set sleep timer Crash

### ISSUE THREAD

**Issue by lushohammy** [gauravjot/android-noad-music-player#3]
**Expected behavior**
it expected that user can use can use set sleep timer with typing 0 without any crash 

**Actual behavior**
the app crash when i type 0 in the set sleep timer

**How to reproduce**
1. open the app
2. then go to Set Sleep timer
3. then type 0
4. note the bug
 
#### device

 - OS: Android 8.1.0
 - app version:  0.9.2019

**Recording Of The Bug**
https://youtu.be/2GHyMO82zCU

**Comment by gauravjot** [comment]
Bug will be squashed in next update I will keep this issue open until then. Thanks a bunch!
