### ISSUE TITLE
App crashes when I turn of the storage permission

### ISSUE THREAD

**Issue by iamowomizz** [gauravjot/android-noad-music-player#7]
### Describe the bug
The app crashes when I turn off the storage permission

### Steps To Reproduce
1. Launch the app 
2. Accept all permissions
3. Then go to the application details of the Noad app
4. Turn off the storage permission 

### Expected behavior
I expect the app not to crash when I turn off the storage permission 

### Device and Version
Device (Infinix s2pro) 
Version (7.0)
App version 0.9.4

**Comment by gauravjot** [comment]
Thank you for opening the issue. I will fix it in next update tonight :)

**Comment by gauravjot** [comment]
The update should be available to you if you are a beta user of the app. It will be pushed to production in the next major update. I am closing this issue now.
